name: remote_log_elastic
description: Persist Flutter app logs in ElasticSearch
version: 1.0.0
author: "Pedro Brasileiro <pedrobrasileiro@gmail.com>"
homepage: http://pedro.brasileiro.nom.br
repository: https://github.com/pedrobrasileiro/remote_log_elastic

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: