name: remote_log_elastic
version: 1.0.1
author: "Pedro Brasileiro <pedrobrasileiro@gmail.com>"
homepage: https://github.com/pedrobrasileiro/remote_log_elastic/wiki
repository: https://github.com/pedrobrasileiro/remote_log_elastic
description: Persist logs of flutter applications in ElasticSearch. With a short initial setup and a direct call, you persist your log in ElasticSearch.

environment:
  sdk: ">=2.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
